### ISSUE TITLE
rc-select/assets/index.css file is missing

### ISSUE THREAD

**Issue by Bnaya** [networknt/react-schema-form-rc-select#1]

**Comment by stevehu** [comment]
The css is part of the rc-select and it should not be included. You need to import it in your app.

**Comment by Bnaya** [comment]
Thanks!

**Comment by Dinal-Fernando** [comment]
rc-select/assets/index.css file is not include in rc-select

**Comment by stevehu** [comment]
@Dinal-Fernando I have just upgraded all the dependencies to the latest for the react-schema-form and I  am working on this repo. Once we upgrade to the latest react-select, everything should be fine.
