### ISSUE TITLE
interested

### ISSUE THREAD

**Issue by ml242** [networknt/react-schema-form-rc-select#5]
Wanted to check out the live demo but the url for the API is down. Do you know if it is still compatible with the newer versions of Mozilla's lib?

**Comment by stevehu** [comment]
@ml242 I am using this in one of my old framework for administration console and I am in a process to move it into my newer frameworks. I will be spending some time to upgrade this to the latest and test it soon. Thanks for your consideration.

**Comment by stevehu** [comment]
I have rebuilt a reference API and updated the live dome to the latest. Check it out the live demo and the full tutorial at https://doc.networknt.com/tutorial/rest/openapi/light-reference/
